### ISSUE TITLE
Next Release

### ISSUE THREAD

**Issue by christianalfoni** [christianalfoni/cerebral-router#44]
- [x] Implement a way to handle redirect as replace instead of push #14
- [x] Add support for basic regexp urls #42
- [x] Fix onlyHash and baseUrl behavior #46 
- [x] Fix query shallow #35 
- [x] get rid of window.location dependency christianalfoni/addressbar/issues/6
- [x] Refactor more tests to secure latest cleanup
- [x] Update documentation
- [x] Add `<Link/>` component to `cerebral-react` christianalfoni/cerebral-react/issues/18

**Comment by Guria** [comment]
update current state in your message
